services:
  - type: web
    name: djossy-de-baby
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djossy.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: djossy-de-baby.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: djossy-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: djossy-db
    databaseName: djossy_db
    user: djossy_user
