services:
  - type: web
    name: djossy-de-baby
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djossy_de_baby.wsgi:application
    envVars:
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: your_database_port

databases:
  - name: djossy-db
    databaseName: djossy_db
    user: djossy_user
