# Generated by Django 5.2 on 2025-05-19 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(verbose_name='Lettre de motivation / message')),
                ('cv', models.FileField(upload_to='cv/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_postulation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatureEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('poste_recherche', models.CharField(choices=[('Servante', 'Servante'), ('Cuisinier', 'Cuisinier'), ('Chauffeur', 'Chauffeur'), ('Gardien', 'Gardien'), ('Autre', 'Autre')], max_length=50)),
                ('experience', models.CharField(choices=[('Débutant', 'Débutant'), ('1-2 ans', '1-2 ans'), ('3-5 ans', '3-5 ans'), ('+5 ans', '+5 ans')], max_length=20)),
                ('localisation', models.CharField(max_length=100)),
                ('disponibilite', models.DateField()),
                ('cv', models.FileField(upload_to='candidatures/cv/')),
                ('photo', models.ImageField(upload_to='candidatures/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEmployeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_personnel', models.CharField(choices=[('Servante', 'Servante'), ('Cuisinier', 'Cuisinier'), ('Chauffeur', 'Chauffeur'), ('Gardien', 'Gardien'), ('Autre', 'Autre')], max_length=50)),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('lieu_affectation', models.CharField(max_length=100)),
                ('duree_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Mission courte', 'Mission courte')], max_length=50)),
                ('salaire_propose', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('exigences', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employeur', models.CharField(max_length=100)),
                ('email_employeur', models.EmailField(max_length=254)),
                ('description_poste', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('experience', models.TextField()),
                ('competences', models.TextField()),
                ('photo', models.ImageField(upload_to='profils_photos/')),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
    ]
