# Generated by Django 5.2 on 2025-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='nouvelle', max_length=20),
        ),
        migrations.AddField(
            model_name='demandepersonnel',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_traitement', 'En traitement'), ('traitee', 'Traitée')], default='nouvelle', max_length=20),
        ),
    ]
