# Generated by Django 5.2 on 2025-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_disponibilite',
            field=models.DateField(blank=True, null=True, verbose_name='Date de disponibilité'),
        ),
        migrations.AddField(
            model_name='profil',
            name='poste_recherche',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste recherché'),
        ),
        migrations.AddField(
            model_name='profil',
            name='salaire_souhaite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire souhaité'),
        ),
    ]
