# Generated by Django 5.2 on 2025-05-24 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_telephone_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profils/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('competences', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
