# Generated by Django 5.2 on 2025-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='cvs_candidatures/')),
                ('lettre_motivation', models.TextField(blank=True)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('description_demande', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profils/')),
                ('description', models.TextField(blank=True)),
                ('competences', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
